name: 'Pop Apple/XCode build'
inputs:
  BuildScheme: 
    required: true
  # this has been made a requirement as you cannot restrict or specify destinations (mac, simulator, ios device) via schemes or configuration
  Destination:
    description: "this becomes the -destination xcodebuild argument, eg. -destination generic/platform=iOS"
    required: true
  Sdk:
    description: "xcodebuild -sdk XXXX, eg. appletvos iphoneos"
    required: false
  Project:
    description: "Path to .xcodeproj. xcodebuild -project $Project.xcodeproj. If not provided xcodebuild looks in current working directory"
    required: false
  ArchiveForTestFlight:
    required: false
    default: false
  AppleID:
    required: false
    default: false
  ApplePassword:
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'
