name: 'Pop Ios build'
inputs:
  BuildScheme: 
    required: true
  project:
    required: true
  ArchiveForTestFlight:
    required: false
    default: false
  AppleID:
    required: false
    default: false
  ApplePassword:
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'
